// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: cMaVBwcHAKAbUiZW5BBnSf
// Component: 8aOTU7GYNG
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Select from "../../Select"; // plasmic-import: KLG_AqYkhWj/component
import Select__Option from "../../Select__Option"; // plasmic-import: RYSuD0jj_2f/component
import Checkbox from "../../Checkbox"; // plasmic-import: 5s3e59b0eE9/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: cMaVBwcHAKAbUiZW5BBnSf/projectcss
import * as sty from "./PlasmicTtt1.module.css"; // plasmic-import: 8aOTU7GYNG/css

export type PlasmicTtt1__VariantMembers = {};

export type PlasmicTtt1__VariantsArgs = {};
type VariantPropType = keyof PlasmicTtt1__VariantsArgs;
export const PlasmicTtt1__VariantProps = new Array<VariantPropType>();

export type PlasmicTtt1__ArgsType = {};
type ArgPropType = keyof PlasmicTtt1__ArgsType;
export const PlasmicTtt1__ArgProps = new Array<ArgPropType>();

export type PlasmicTtt1__OverridesType = {
  root?: p.Flex<"div">;
  select?: p.Flex<typeof Select>;
  checkbox?: p.Flex<typeof Checkbox>;
};

export interface DefaultTtt1Props {
  className?: string;
}

function PlasmicTtt1__RenderFunc(props: {
  variants: PlasmicTtt1__VariantsArgs;
  args: PlasmicTtt1__ArgsType;
  overrides: PlasmicTtt1__OverridesType;
  dataFetches?: PlasmicTtt1__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Select
        data-plasmic-name={"select"}
        data-plasmic-override={overrides.select}
        className={classNames("__wab_instance", sty.select)}
      />

      <Checkbox
        data-plasmic-name={"checkbox"}
        data-plasmic-override={overrides.checkbox}
        className={classNames("__wab_instance", sty.checkbox)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "select", "checkbox"],
  select: ["select"],
  checkbox: ["checkbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  select: typeof Select;
  checkbox: typeof Checkbox;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTtt1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTtt1__VariantsArgs;
    args?: PlasmicTtt1__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTtt1__Fetches;
  } & Omit<PlasmicTtt1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTtt1__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTtt1__ArgProps,
      internalVariantPropNames: PlasmicTtt1__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTtt1__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTtt1";
  } else {
    func.displayName = `PlasmicTtt1.${nodeName}`;
  }
  return func;
}

export const PlasmicTtt1 = Object.assign(
  // Top-level PlasmicTtt1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    select: makeNodeComponent("select"),
    checkbox: makeNodeComponent("checkbox"),

    // Metadata about props expected for PlasmicTtt1
    internalVariantProps: PlasmicTtt1__VariantProps,
    internalArgProps: PlasmicTtt1__ArgProps
  }
);

export default PlasmicTtt1;
/* prettier-ignore-end */
